### PR TITLE
Do not force error values

### PR DESCRIPTION
**Pull request by dy**
UX is everything:

``` js
almost(a, b);
almost(a, b, 0.1);
```

@mikolalysenko, @rreusser  please have a look)

### CODE REVIEW

**Comment by dy** [comment]
@mikolalysenko ok I merge it?

**Comment by dy** [comment]
@mikolalysenko any thoughts on that? Could you add me to the contributors on the npm?

**Comment by rreusser** [comment]
Thoughts:
- Overall, I think it makes sense, but it's a matter of style preference whether there should be a default. For most cases though, I think this matches how people will be interested in using it.
- Should it be `DBL_EPSILON` by default since that's the default floating point precision for js?
- Could you amend the docs as `almostEqual(a, b [, absoluteTolerance [, relativeTolerance]])` with the corresponding notes?

**Comment by dy** [comment]
@rreusser done. Could you please publish it to npm or grant me an access?

**Comment by rreusser** [comment]
I don't have access to my computer at the moment but will add you as a collaborator ASAP! Sorry about that! Just spent two weeks on jury duty so I'm not performing admirably on side projects at the moment. :disappointed:  In the mean time, can you confirm the compatibility of the API? This is just a matter of useful defaults, right? Was there a default assumption (zeros, perhaps) that this will break, or was blank simply invalid previously?

**Comment by dy** [comment]
It was invalid, so it is a minor API change

**Comment by rreusser** [comment]
Sorry for the delay! I've added you as a collaborator on npm/almost-equal. A default makes sense and looks good to me, so I think publishing is the right move. Unfortunately that doesn't add you across the board on npmjs.com, but I think I have access to most things, so I'm glad to add you as a collaborator and offer a second opinion on other thigns if I can! Thanks!

:+1:

**Comment by rreusser** [comment]
Sorry, so to clarify, I'm glad to do the honors if you like, but if you have the privileges and want to, I say merge and publish!

**Comment by dy** [comment]
@rreusser thank you for the review! Done.

**Pull request merged**
